-- Fresh reseed of car data with proper images
DELETE FROM public.cars;

INSERT INTO public.cars (brand, model, year, price, mileage, engine, transmission, fuel_type, interior_color, exterior_color, description, features, images, is_featured, is_sold)
VALUES 
  (
    'Mercedes-Benz',
    'S-Class 2024',
    2024,
    45000000.00,
    50,
    '3.0L V6 Turbo',
    'Automatic',
    'Petrol',
    'Black Leather',
    'Midnight Black',
    'Luxury sedan with advanced technology, premium sound system, and adaptive air suspension. Perfect for executive travel.',
    ARRAY['Panoramic Sunroof', 'Leather Interior', 'Touch Infotainment', 'Adaptive Suspension', '360 Camera', 'Heated Seats', 'Cruise Control'],
    ARRAY['https://images.unsplash.com/photo-1617469767537-b85461a1bbe0?w=800&q=80'],
    true,
    false
  ),
  (
    'BMW',
    'X7 2024',
    2024,
    52000000.00,
    30,
    '4.4L V8 Twin-Turbo',
    'Automatic',
    'Petrol',
    'Cream Leather',
    'Pearl White',
    'Powerful SUV with cutting-edge technology and premium comfort. Ideal for luxury family travel.',
    ARRAY['Panoramic Sunroof', 'Leather Interior', 'iDrive System', 'Adaptive Suspension', 'Parking Assistant', 'Premium Sound', 'Heated Seats'],
    ARRAY['https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=800&q=80'],
    true,
    false
  ),
  (
    'Lexus',
    'RX 500h 2024',
    2024,
    55000000.00,
    25,
    '3.5L V6 Hybrid',
    'Automatic',
    'Hybrid',
    'Walnut Brown',
    'Silver',
    'Premium hybrid SUV with exceptional reliability and performance. Features advanced safety technology.',
    ARRAY['Panoramic Roof', 'Luxury Interior', 'Hybrid Engine', 'Adaptive Suspension', 'Pre-Collision System', 'Mark Levinson Audio', 'Climate Control'],
    ARRAY['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80'],
    false,
    false
  ),
  (
    'Audi',
    'Q8 2024',
    2024,
    48000000.00,
    40,
    '3.0L V6 Turbo',
    'Automatic',
    'Petrol',
    'Black Nappa',
    'Graphite Black',
    'Elegant coupe SUV with distinctive design and dynamic performance. Premium technology throughout.',
    ARRAY['Panoramic Sunroof', 'Leather Seats', 'Virtual Cockpit', 'Adaptive Air Suspension', 'Bang & Olufsen Audio', '360 Camera', 'Matrix LED'],
    ARRAY['https://images.unsplash.com/photo-1606611013016-969c19d14319?w=800&q=80'],
    false,
    false
  ),
  (
    'Porsche',
    'Cayenne Turbo 2024',
    2024,
    58000000.00,
    15,
    '4.0L V8 Twin-Turbo',
    'Automatic',
    'Petrol',
    'Black Leather',
    'Racing Yellow',
    'High-performance SUV with sports car DNA. Exceptional acceleration and handling.',
    ARRAY['Air Suspension', 'Leather Interior', 'Turbocharger', 'Adaptive Dynamics', 'Panoramic Roof', 'Premium Audio', 'Sports Exhaust'],
    ARRAY['https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800&q=80'],
    true,
    false
  ),
  (
    'Range Rover',
    'Sport SVR 2024',
    2024,
    50000000.00,
    20,
    '5.0L V8 Supercharged',
    'Automatic',
    'Petrol',
    'Ebony Leather',
    'Fuji White',
    'Iconic SUV combining luxury with unmatched off-road capability. Commanding presence.',
    ARRAY['All-Terrain Response', 'Leather Seats', 'Panoramic Roof', 'Merlin Suspension', 'Meridian Audio', 'Terrain Management', 'Night Vision'],
    ARRAY['https://images.unsplash.com/photo-1605559424843-9e4c3ca856d1?w=800&q=80'],
    false,
    false
  ),
  (
    'Rolls-Royce',
    'Phantom 2024',
    2024,
    85000000.00,
    5,
    '6.7L V12 Twin-Turbo',
    'Automatic',
    'Petrol',
    'Bespoke Cream',
    'Diamond Black',
    'The pinnacle of luxury automobiles. Unparalleled craftsmanship and exclusivity.',
    ARRAY['Bespoke Interior', 'Starlight Headliner', 'Self-Closing Doors', 'Adaptive Air Suspension', 'Rear Entertainment', 'Premium Audio', 'Climate Seats'],
    ARRAY['https://images.unsplash.com/photo-1605559424843-9e4c3ca856d1?w=800&q=80'],
    true,
    false
  ),
  (
    'Bentley',
    'Bentayga Speed 2024',
    2024,
    68000000.00,
    10,
    '6.0L W12 Twin-Turbo',
    'Automatic',
    'Petrol',
    'Oyster Leather',
    'Satin Moonlight',
    'British luxury SUV with handcrafted elegance. Designed for the discerning clientele.',
    ARRAY['Handcrafted Interior', 'Panoramic Roof', 'Active Suspension', 'Mulliner Specifications', 'Premium Audio', 'Massage Seats', 'All-Weather Capability'],
    ARRAY['https://images.unsplash.com/photo-1609708536573-a4787e2355a7?w=800&q=80'],
    true,
    false
  ),
  (
    'Tesla',
    'Model S Plaid 2024',
    2024,
    42000000.00,
    100,
    'Tri Motor',
    'Automatic',
    'Electric',
    'Black Vegan Leather',
    'Ultra White',
    'Revolutionary electric sedan with incredible performance. Zero emissions, maximum efficiency.',
    ARRAY['Tri Motor', 'Autopilot', 'Panoramic Glass', 'Premium Audio', 'Over-the-air Updates', 'Touchscreen Control', 'Supercharging'],
    ARRAY['https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=800&q=80'],
    false,
    false
  ),
  (
    'Lamborghini',
    'Urus S 2024',
    2024,
    75000000.00,
    8,
    '4.0L V8 Twin-Turbo',
    'Automatic',
    'Petrol',
    'Black Alcantara',
    'Rosso Corsa',
    'Super SUV with Italian passion. Breathtaking performance and striking design.',
    ARRAY['Carbon Fiber', 'Magnetic Suspension', 'Rotund Control', 'Leather Interior', 'Premium Audio', 'Panoramic Roof', 'Air Suspension'],
    ARRAY['https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800&q=80'],
    true,
    false
  );

SELECT COUNT(*) as total_cars FROM public.cars;
